FROM alpine:3.18

RUN apk add --no-cache git python3

RUN git clone https://github.com/SulaimanMehshooq/github-fundamentals.git /repo

WORKDIR /app
RUN cp /repo/docker_playground/hello.py ./hello.py

CMD ["python3", "hello.py"]
